# Generated by Django 5.0.2 on 2024-02-24 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=256)),
                ('stage_status', models.IntegerField()),
                ('date', models.CharField(max_length=256, null=True)),
                ('sessionStartDate', models.CharField(max_length=256, null=True)),
                ('sessionEndDate', models.CharField(max_length=256, null=True)),
                ('stage_project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parsing.projects')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.DeleteModel(
            name='Stages',
        ),
    ]
