# Generated by Django 5.0.2 on 2024-02-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_tag', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='OntologySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_tag', models.CharField(max_length=256)),
            ],
        ),
    ]
